# Generated by Django 4.1.4 on 2023-01-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover',
        ),
    ]
